"use client";
import { FormEvent, useState } from "react";
import { Check, Pencil, Plus, X } from "lucide-react";
import type { CatalogProduct, ProductCategory } from "@/lib/catalog/product-repository";
import { EDITOR_TYPES, PRODUCT_STATUSES, type EditorType, type ProductStatus } from "@/lib/catalog/product-input";

type EditorProduct = Partial<CatalogProduct> & { id:string;slug:string;name:string;description:string;priceSatang:number;categoryId:string;status:ProductStatus;sortOrder:number;editorType:EditorType;accent:string;badge:string };
const EMPTY:EditorProduct={id:"",slug:"",name:"",description:"",priceSatang:0,categoryId:"",status:"COMING_SOON",sortOrder:10,editorType:"MUG_3D",accent:"#dce8d5",badge:"เร็ว ๆ นี้"};
export default function ProductManager({products,categories}:{products:CatalogProduct[];categories:ProductCategory[]}){
 const [editing,setEditing]=useState<EditorProduct|null>(null);const [error,setError]=useState("");const [isSaving,setIsSaving]=useState(false);
 function open(product?:CatalogProduct){setError("");setEditing(product?{...product}: {...EMPTY,categoryId:categories[0]?.id||""})}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;setIsSaving(true);setError("");const isNew=!products.some(product=>product.id===editing.id);const response=await fetch(isNew?"/api/admin/products":`/api/admin/products/${editing.id}`,{method:isNew?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(editing)});const result=await response.json();if(!response.ok){setError(result.error||"บันทึกไม่สำเร็จ");setIsSaving(false);return}location.reload()}
 return <div className="admin-products"><div className="admin-products-toolbar"><div><p className="eyebrow">CATALOG MANAGER</p><h1>สินค้าและหมวด</h1><p>จัดสินค้าในหน้าแรก ราคา ลำดับ และสถานะหน้าออกแบบ</p></div><button className="primary" onClick={()=>open()}><Plus/> เพิ่มสินค้า</button></div>{categories.map(category=><section className="admin-category" key={category.id}><header><div><small>หมวดสินค้า</small><h2>{category.name}</h2></div><span>{products.filter(product=>product.categoryId===category.id).length} รายการ</span></header><div>{products.filter(product=>product.categoryId===category.id).map(product=><article key={product.id}><i style={{background:product.accent}}/><div><small>{product.slug}</small><h3>{product.name}</h3><p>{product.description}</p></div><strong>฿{(product.priceSatang/100).toLocaleString("th-TH")}</strong><span className={`admin-product-status ${product.status.toLowerCase()}`}>{product.status==="AVAILABLE"?<Check/>:null}{product.status}</span><button onClick={()=>open(product)}><Pencil/> แก้ไข</button></article>)}</div></section>)}
 {editing&&<div className="overlay"><form className="admin-product-modal" onSubmit={save}><header><div><p className="eyebrow">PRODUCT</p><h2>{products.some(product=>product.id===editing.id)?"แก้ไขสินค้า":"เพิ่มสินค้า"}</h2></div><button type="button" onClick={()=>setEditing(null)} aria-label="ปิด"><X/></button></header><div className="admin-product-fields"><label>รหัสสินค้า<input value={editing.id} disabled={products.some(product=>product.id===editing.id)} onChange={e=>setEditing({...editing,id:e.target.value,slug:e.target.value})} required/></label><label>Slug<input value={editing.slug} onChange={e=>setEditing({...editing,slug:e.target.value})} required/></label><label className="full">ชื่อสินค้า<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} required/></label><label className="full">คำอธิบาย<textarea rows={3} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>ราคา (บาท)<input type="number" min="0" value={editing.priceSatang/100} onChange={e=>setEditing({...editing,priceSatang:Math.round(Number(e.target.value)*100)})}/></label><label>หมวด<select value={editing.categoryId} onChange={e=>setEditing({...editing,categoryId:e.target.value})}>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>สถานะ<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as ProductStatus})}>{PRODUCT_STATUSES.map(status=><option key={status}>{status}</option>)}</select></label><label>ประเภท Editor<select value={editing.editorType} onChange={e=>setEditing({...editing,editorType:e.target.value as EditorType})}>{EDITOR_TYPES.map(type=><option key={type}>{type}</option>)}</select></label><label>ลำดับ<input type="number" min="0" value={editing.sortOrder} onChange={e=>setEditing({...editing,sortOrder:Number(e.target.value)})}/></label><label>สีการ์ด<input type="color" value={editing.accent} onChange={e=>setEditing({...editing,accent:e.target.value})}/></label><label className="full">ป้ายสินค้า<input value={editing.badge} onChange={e=>setEditing({...editing,badge:e.target.value})}/></label></div>{editing.status==="AVAILABLE"&&!editing.hasTemplate&&<p className="admin-warning">สินค้านี้ยังไม่มี template งานผลิต จึงเปิด AVAILABLE ไม่ได้</p>}{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={isSaving}>{isSaving?"กำลังบันทึก…":"บันทึกสินค้า"}</button></form></div>}
 </div>
}
