CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE order_status AS ENUM ('PENDING_PAYMENT','PAID','DESIGN_APPROVED','PRINTING','PRINTED','PACKING','SHIPPED','COMPLETED','CANCELLED');
CREATE TYPE payment_status AS ENUM ('PENDING','UNDER_REVIEW','PAID','REJECTED','REFUNDED');
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE, name text NOT NULL, phone text, role text NOT NULL DEFAULT 'CUSTOMER', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE product_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, sort_order integer NOT NULL DEFAULT 0);
CREATE TABLE products (id text PRIMARY KEY, slug text UNIQUE NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', price_satang integer NOT NULL CHECK(price_satang>=0), active boolean NOT NULL DEFAULT true, category_id uuid REFERENCES product_categories(id), status text NOT NULL DEFAULT 'DRAFT', sort_order integer NOT NULL DEFAULT 0, editor_type text NOT NULL DEFAULT 'MUG_3D', accent text NOT NULL DEFAULT '#dce8d5', badge text NOT NULL DEFAULT '', image_path text, image_styles jsonb NOT NULL DEFAULT '{}', print_options jsonb NOT NULL DEFAULT '[{"type":"ONE_SIDE","label":"1 ด้าน","priceSatang":15000,"isEnabled":true,"widthCm":8,"heightCm":8},{"type":"TWO_SIDES","label":"2 ด้าน","priceSatang":18000,"isEnabled":true,"widthCm":20,"heightCm":9},{"type":"FULL_WRAP","label":"รอบแก้ว","priceSatang":19900,"isEnabled":true,"widthCm":20,"heightCm":9}]', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE site_media (media_key text PRIMARY KEY, storage_path text NOT NULL, content_type text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE product_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id text NOT NULL REFERENCES products(id), version integer NOT NULL, mug_config jsonb NOT NULL, print_config jsonb NOT NULL, model_config jsonb NOT NULL, uv_config jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(product_id,version));
CREATE TABLE designs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id text NOT NULL REFERENCES products(id), template_id uuid NOT NULL REFERENCES product_templates(id), user_id uuid REFERENCES users(id), fabric_json jsonb NOT NULL, asset_refs jsonb NOT NULL DEFAULT '[]', print_width_cm numeric(8,3) NOT NULL, print_height_cm numeric(8,3) NOT NULL, dpi integer NOT NULL, preview_path text NOT NULL, print_path text NOT NULL, print_option text NOT NULL DEFAULT 'FULL_WRAP' CHECK(print_option IN ('ONE_SIDE','TWO_SIDES','FULL_WRAP')), print_placement text, unit_price_satang integer NOT NULL DEFAULT 19900, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE design_assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), design_id uuid NOT NULL REFERENCES designs(id) ON DELETE CASCADE, storage_path text NOT NULL, mime_type text NOT NULL, original_name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_number text UNIQUE NOT NULL, user_id uuid REFERENCES users(id), status order_status NOT NULL DEFAULT 'PENDING_PAYMENT', customer_name text NOT NULL, email text, phone text NOT NULL, shipping_address jsonb NOT NULL, subtotal_satang integer NOT NULL, shipping_satang integer NOT NULL, total_satang integer NOT NULL, note text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id text NOT NULL REFERENCES products(id), design_id uuid NOT NULL REFERENCES designs(id), product_snapshot jsonb NOT NULL, design_snapshot jsonb NOT NULL, quantity integer NOT NULL CHECK(quantity>0), unit_price_satang integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid NOT NULL REFERENCES orders(id), method text NOT NULL DEFAULT 'PROMPTPAY', status payment_status NOT NULL DEFAULT 'PENDING', amount_satang integer NOT NULL, slip_path text, paid_at timestamptz, reviewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE shipments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), order_id uuid UNIQUE NOT NULL REFERENCES orders(id), carrier text, tracking_number text, shipped_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO products(id,name,description,price_satang) VALUES ('ceramic-mug-11oz','แก้วเซรามิก 11 oz','แก้วเซรามิกสีขาว พิมพ์ลายรอบใบ',29900) ON CONFLICT DO NOTHING;
INSERT INTO product_templates(product_id,version,mug_config,print_config,model_config,uv_config)
SELECT 'ceramic-mug-11oz',1,'{"capacityOz":11,"diameterCm":8.4,"heightCm":9.5}','{"widthCm":20,"heightCm":9,"dpi":300,"safeMarginCm":0.3,"bleedCm":0.2}','{"path":"/models/mug-11oz.glb?v=7","printMaterial":"MugBodyPrint","ceramicMaterial":"MugCeramic","handleMaterial":"MugHandle"}','{"offsetX":0.25,"offsetY":0,"repeatX":1,"repeatY":1,"rotation":0}' WHERE NOT EXISTS(SELECT 1 FROM product_templates WHERE product_id='ceramic-mug-11oz' AND version=1);
CREATE INDEX orders_status_created_idx ON orders(status,created_at DESC); CREATE INDEX designs_product_idx ON designs(product_id,created_at DESC);
