"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Check, ChevronLeft, Minus, Plus } from "lucide-react";

type CompletedOrder={orderNumber:string;totalSatang:number};
export default function CheckoutForm({designId}:{designId:string}){
  const [qty,setQty]=useState(1);const [busy,setBusy]=useState(false);const [done,setDone]=useState<CompletedOrder|null>(null);const [qr,setQr]=useState("");const [phone,setPhone]=useState("");const [slipSent,setSlipSent]=useState(false);const [error,setError]=useState("");
  const subtotal=299*qty,shipping=subtotal>=999?0:60,total=subtotal+shipping;
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget);setPhone(String(data.get("phone")));const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({designId,quantity:qty,customerName:data.get("name"),email:data.get("email"),phone:data.get("phone"),address:{line1:data.get("address"),district:data.get("district"),province:data.get("province"),postalCode:data.get("postal")},note:data.get("note")})});const result=await response.json();if(!response.ok){setError(result.error);setBusy(false);return}setDone(result);const qrResult=await fetch(`/api/payment-qr?amount=${result.totalSatang/100}`).then(r=>r.json());setQr(qrResult.dataUrl||"")}
  async function uploadSlip(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!done)return;setError("");const form=new FormData(e.currentTarget);form.set("phone",phone);const response=await fetch(`/api/orders/${done.orderNumber}/slip`,{method:"POST",body:form});const result=await response.json();if(response.ok)setSlipSent(true);else setError(result.error)}
  if(done)return <main className="checkout-page"><div className="payment-card"><div className="success-mark"><Check/></div><h1>สร้างคำสั่งซื้อแล้ว</h1><p>หมายเลขคำสั่งซื้อ <b>{done.orderNumber}</b></p>{qr?<><Image className="qr" src={qr} alt="PromptPay QR" width={260} height={260} unoptimized/><h2>ยอดชำระ ฿{(done.totalSatang/100).toLocaleString("th-TH")}</h2><p>สแกน PromptPay แล้วแนบสลิปด้านล่าง</p></>:<p className="notice">ร้านยังไม่ได้ตั้งค่า PromptPay กรุณาติดต่อร้านพร้อมแจ้งเลขออเดอร์</p>}{slipSent?<p className="slip-success"><Check/> ส่งสลิปแล้ว ร้านจะตรวจสอบยอด</p>:<form className="slip-form" onSubmit={uploadSlip}><label>แนบสลิป<input name="slip" type="file" accept="image/png,image/jpeg" required/></label><button className="download-button">ส่งสลิป</button></form>}{error&&<p className="form-error">{error}</p>}<Link className="primary" href={`/orders/${done.orderNumber}`}>ติดตามคำสั่งซื้อ</Link></div></main>;
  return <main className="checkout-page"><form className="checkout-card" onSubmit={submit}><Link href="/design" className="back-link"><ChevronLeft/> กลับไปแก้แบบ</Link><p className="eyebrow">CHECKOUT</p><h1>ข้อมูลจัดส่ง</h1><div className="order-summary"><Image src={`/api/designs/${designId}/preview`} alt="แบบแก้ว" width={110} height={62} unoptimized/><div><b>แก้วเซรามิก 11 oz</b><small>พิมพ์ลายรอบใบ</small><div className="quantity"><button type="button" onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button type="button" onClick={()=>setQty(qty+1)}><Plus/></button></div></div><strong>฿{subtotal.toLocaleString("th-TH")}</strong></div><div className="checkout-fields"><label>ชื่อผู้รับ<input name="name" required/></label><label>เบอร์โทร<input name="phone" required/></label><label className="full">อีเมล (ถ้ามี)<input name="email" type="email"/></label><label className="full">ที่อยู่<textarea name="address" rows={3} required/></label><label>อำเภอ/เขต<input name="district" required/></label><label>จังหวัด<input name="province" required/></label><label>รหัสไปรษณีย์<input name="postal" inputMode="numeric" required/></label><label>หมายเหตุ<input name="note"/></label></div><div className="checkout-total"><p><span>สินค้า</span><b>฿{subtotal.toLocaleString("th-TH")}</b></p><p><span>ค่าจัดส่ง</span><b>{shipping?`฿${shipping}`:"ฟรี"}</b></p><div><span>ยอดรวม</span><strong>฿{total.toLocaleString("th-TH")}</strong></div></div>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?"กำลังสร้างออเดอร์…":"ยืนยันคำสั่งซื้อ"}</button></form></main>;
}
